### ISSUE TITLE
R pkg vs API

### ISSUE THREAD

**Issue by jimrothstein** [JosiahParry/opensecrets#2]
Seems to be good match between the **R functions** you wrote AND **API methods** listed on website here (https://www.opensecrets.org/api/admin/index.php?function=user_api_list).

Wrote code to use R functions in cand_contrib.R and get_legislators.R:    seems to be working nicely.

Few cosmetic items (in next  Issue) and still getting to know API, but think you did a very good job and no surprises (yet)
jim

**Comment by JosiahParry** [comment]
Hi Jim, I am unsure what this issue is related to. Closing as there is nothing to fix!

Thanks :)
