### ISSUE TITLE
DESCRIPTION missing imports

### ISSUE THREAD

**Issue by jimrothstein** [JosiahParry/opensecrets#3]
All seems to work,  but the R pkgs book v2 (by Hadley & Jenny Bryan) suggests:

Imports:  (in DESCRIPTION file)   and then using   purrr::pluck()  form.
(see Chapter 11.6) (https://r-pkgs.org/namespace.html)
Think the usethis::use_package()  does this.

Rather than @importFrom   

I'm neutral, just mentioning this.

**Comment by JosiahParry** [comment]
The Imports is indeed missing from the DESCRIPTION file. They are present at the individual function documentation level. If you're able please submit a PR with the required packages in the Imports list. 

How you do that is up to you :)

**Comment by jimrothstein** [comment]
Will add imports: to DESCRIPTION.

**### Please note:   Branches:**
On my local machine (laptop),  I have **'master' b**ranch, which is I hope to keep synced with your work.   So I will *never* do my own work on this.

I have a second branch on my laptop, **"jim_main".**   This is where I do my work.

I would appreciate a bit of guidance on HOW to to push(?) this so that you can review and merge as appropriate.  Thx.

**UPDATE**
Added imports:   to DESCRIPTION.   Want to 'squash' commit comments  so looks cleaner.   Then  push(?) to you, somehow.

**UPDATE 2 **
Have clean local branch and would like to push to you.   Not sure how to do.  
Rejecting:   
git push  upstream jim_Main

**Comment by JosiahParry** [comment]
Hi Jim,

You do not have write access to my repository so no need to be concerned there. You will need to create what is called a pull request to merge your changes into you my repository. The first step to do that will be to actually push those commits to a branch. In your example you'd need to write `git push origin jim_main` to push the commits to that branch.

But if you'd like to clean up your commit history, I'd recommend copying your modified files to a new location, switching to your master branch (which seems to be untouched) and then putting the changed files in that location. Once you've do that, push your changes to your master branch. (you can just write `git push`). 

If you're satisfied navigate to your repository in GitHub and then click the  green `create pull request` button. That will begin the process. 

Here is a resource that might be of assistance https://opensource.com/article/19/7/create-pull-request-github. Additionally Jenny's book [Happy Git with R](https://happygitwithr.com/) is a super solid resource.
